print("EXAMPLE 1")
name=input("What is your name?")
print(f"Hello {name} and welcome to CT8")
print("Today we will tell a story with your help")
print("")
print("----------------------------------------------------------------")
print("")
animal=input("Pick an animal: ")
transportation=input("Pick a mode of transportation: ")
job=input("Pick a job: ")
food=input("Pick a food: ")
emotion=input("Pick an emotion: ")
adjective=input("Pick a adjective: ")
city=input("Pick a city: ")
sport=input("pick a sport: ")
animal2=input("Pick another animal: ")
dessert=input("pick a dessert: ")
print("")
print("----------------------------------------------------------------")
print("")
print(f"One day, a {animal} went to work. There job is {job} so they where very {emotion}. To get to work the {animal} uses a {transportation}. They also decided they were hungry so the {animal} ate {food}, it was very {adjective}. After work the {animal} went to {city} to watch a {sport} game. At the {sport} game the {animal} met a {animal2} and they became friends. Afterwords they decided to get {dessert}. When the {animal} got home they went to bed.")
print("The End")